version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - hndoss
  ignore:
  - dependency-name: is-svg
    versions:
    - 4.3.1
